apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multigres-dev-user
namePrefix: multigres-dev-user-

resources:
- ../namespaced

images:
- name: ghcr.io/multigres/multigres-operator
  newName: registry.example.com/multigres-operator
  newTag: branch
